### ISSUE TITLE
Agregar título y texto de la unidad de paisaje.

### ISSUE THREAD

**Issue by eliocamp** [prosathumedales/catalogo_SARespectral#1]
"Al seleccionar la unidad, debería aparecer un título de la unidad de paisaje y un breve texto."

Falta que Natalia me pase los textos.

**Comment by nmorandeira** [comment]
Agregué los textos acá: https://github.com/prosathumedales/catalogo_SARespectral/blob/main/datos/textos_descriptivos.docx
