### ISSUE TITLE
Cambiar el dominio de la web

### ISSUE THREAD

**Issue by nmorandeira** [prosathumedales/catalogo_SARespectral#23]
Si se puede poner con este dominio, mejor -avisame si tengo que hacer algo @eliocamp 
https://prosathumedales.shinyapps.io/conae/

**Comment by eliocamp** [comment]
Si creaste la cuenta prosathumedales en shinyapps, creo que podés agegar mi usuario (eliocamp) al equipo o algo así y entonces puedo hacer el deploy ahí. Sino, pasame las credenciales de la cuenta por whatsapp y me fijo.

**Comment by nmorandeira** [comment]
ahí creé la cuenta. Te paso las credenciales!

**Comment by eliocamp** [comment]
Cerrado por ce74978e23da1a66e4287d97bb65bea749769ff4
