### ISSUE TITLE
Datos ópticos - Título de eje-y y valor de índices sintéticos

### ISSUE THREAD

**Issue by nmorandeira** [prosathumedales/catalogo_SARespectral#29]
- En las Firmas espectrales, debería decir "**Reflectancia (%)**". En lo posible agregar el tick y valor 40.

- En la serie temporal, debería decir "**Índice sintético**"  y los valores deberían estar entre 1 y -1. ¿Quizás aplicaste el escalado logartimico que tenían los datos SAR? Estos datos no requieren de conversión

**Comment by eliocamp** [comment]
Perfecto. ahora los datos ópticos los multiplico por 0.01 pero sólo las bandas (no los índices sintéticos). Luego los ploteo así como van. 

Para los datos SAR, la líena de tiempo la hago calculando promedios para cada fecha, polarización y tipo de humedal. En esos estoy primero calculando los decibeles y luego el promedio.

**Comment by eliocamp** [comment]
Ok, ahí lo cambié en la última vesión.
