### ISSUE TITLE
Agregar zonas

### ISSUE THREAD

**Issue by eliocamp** [prosathumedales/catalogo_SARespectral#31]
En datos ahora hay subcarpetas con la información de cada zona. Por ahora está delta_superior. La carpeta concepcion tiene lo mismo que delta_superior y está ahí de placeholder con una copia mínimamente modificada de los datos de delta_superior.

**Comment by eliocamp** [comment]
@nmorandeira En los datos que me pasaste de concepción del Uruguay hay algunas inconsistencias en los nombres de `tipo_humed`:

```
[1] "Depósitos_fluviales_con_bosques"          
[2] "Bajos_con_praderas_de_herbáceas_y_leñosas"
[3] "Lagunas"                                  
[4] "Riberas_con_bosques"                      
[5] "Cañadas_con_leñosas_y_herbáceas"          
[6] "No_humedales"                             
[7] "No_humedal"                               
[8] "Bajos_con_praderas_herbáceas_y_leñosas"   
[9] "Riberas_con_bosque"
````
`Bajos_con_praderas_herbáceas_y_leñosas` aparece también como "Bajos_con_praderas_**de**_herbáceas_y_leñosas" en los datos y como "Bajos_con_praderas_de_herbáceas_**hidrófilas**_y_leñosas" en  textos_humedales.yaml.

`Riberas_con_bosques` aparece como "Riberas_con_bosque" (sin s al final).

Modifiqué los  textos_humedales.yaml y agregué un paso de procesamiento de datos para corregirlos. Quizás es algo igual que hay que arreglar en los datos entrantes.

**Comment by nmorandeira** [comment]
Hice lío con las etiquetas… Lo arreglaste con prepocesamiento entonces, o
querés que las corrija?

**Comment by eliocamp** [comment]
Lo arreglé en preprocesamiento, pero estaría bueno que venga arreglado en la próxima actualización.
